version: '2.1'

volumes:
  pgdata:
  walletstore:

networks:
  universidades_network:
    external:
      name: fabric_test

services:
  explorerdb.universidades.com:
    image: hyperledger/explorer-db:latest
    container_name: explorerdb.universidades.com
    hostname: explorerdb.universidades.com
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - universidades_network

  explorer.universidades.com:
    image: hyperledger/explorer:latest
    container_name: explorer.universidades.com
    hostname: explorer.universidades.com
    environment:
      - DATABASE_HOST=explorerdb.universidades.com
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ./explorer-config.json:/opt/explorer/app/platform/fabric/config.json
      - ./explorer-connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ../organizations:/opt/explorer/organizations
      - walletstore:/opt/explorer/wallet
    ports:
      - 8080:8080
    depends_on:
      explorerdb.universidades.com:
        condition: service_healthy
    networks:
      - universidades_network 